name: wpe-webkit-mir-kiosk
base: core18
version: "2.22.5" # wpe-webkit release version. TODO: use adopt-info
summary: WPE Webkit in kiosk mode. Intended for mir-kiosk on embedded devices.
description: |
  'WPE Webkit (https://wpewebkit.org) is an official fork of the WebKit project.
  From the website: “WPE WebKit allows embedders to create simple and performant
  systems based on Web platform technologies. It is designed with hardware
  acceleration in mind, leveraging common 3D graphics APIs for best
  performance.”
  This snap runs the included MiniBrowser as a service in kiosk mode.'

grade: devel
confinement: strict

# TODO: Check if these paths can be made relative with compiler flags
layout:
  # Relies on cmake install prefix $SNAP/usr, /libexec is not allowed
  /usr/libexec/wpe-webkit-0.1:
    bind: $SNAP/usr/libexec/wpe-webkit-0.1
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/wpe-webkit-0.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/wpe-webkit-0.1
  /etc/fonts/conf.avail:
    bind: $SNAP/etc/fonts/conf.avail
  /etc/ssl/certs/ca-certificates.crt:
    bind-file: $SNAP/etc/ssl/certs/ca-certificates.crt
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/local/share/fonts: # wpe-webkit: Search ALL the fonts!
    bind: $SNAP/usr/share/fonts

apps:
  browser:
    command: desktop-launch $SNAP/bin/snapcraft-preload $SNAP/bin/launch-wpe
    daemon: simple
    restart-condition: always
    plugs:
      # Auto-connected
      - wayland
      - opengl # required for libEGL to work
      - network
      - network-bind # Remote inspector
      - upower-observe
      # Manually connected, show up as AppArmor denials but
      # basic browsing seems to work fine without
      - avahi-observe # zeroconf name resolution
      # snappy-debug suggestions
      - network-manager
      - hostname-control
      - process-control

    environment:
      LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
      # cf. https://tutorials.ubuntu.com/tutorial/wayland-kiosk#9
      # Liberally adapted from
      # https://github.com/MirServer/mir-kiosk-apps/blob/master/snap/snapcraft.yaml
      # Some might not be needed, but omitting some would either crash
      # the WPE renderer process or cause AppArmor denials
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
      XKB_CONFIG_ROOT: ${SNAP}/usr/share/X11/xkb
      XDG_CONFIG_DIRS: ${SNAP}/etc/xdg:$XDG_CONFIG_DIRS
      XDG_DATA_DIRS: ${SNAP}/usr/share:$XDG_DATA_DIRS
      XDG_DATA_HOME: ${SNAP}/usr/share
      XDG_CACHE_HOME: $SNAP_COMMON/cache
      FONTCONFIG_PATH: ${SNAP}/etc/fonts/conf.d
      FONTCONFIG_FILE: ${SNAP}/etc/fonts/fonts.conf

parts:
  # NOTICE: LP builders only get 2h of internet access,
  # so all online sources need to be fetched before wpe-webkit is built.
  # Uses after chaining to ensure everything is pulled before the long build.
  desktop-gtk3:
    # TODO: Check if one of the slimmer desktop helpers works as well
    # https://aur.archlinux.org/packages/wpebackend-fdo/ => packaged by aperezdc, try to map to Ubuntu repos
    build-packages:
      - build-essential
      - libgtk-3-dev
    make-parameters:
      - FLAVOR=gtk3
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - fcitx-frontend-gtk3

  snapcraft-preload:
    after: [desktop-gtk3]
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    build-packages:
      - on amd64:
          - gcc-multilib
          - g++-multilib

  libwpe:
    after: [snapcraft-preload]
    plugin: cmake
    # latest stable release
    source: https://wpewebkit.org/releases/libwpe-1.0.0.tar.xz
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -GNinja
    build-packages:
      - build-essential
      - libegl1
      - libegl1-mesa-dev
      - libglib2.0-dev
      - libxkbcommon-dev
    stage-packages:
      - libxkbcommon0

  wpebackend-fdo:
    after: [libwpe]
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -GNinja
    # latest stable release
    source: https://wpewebkit.org/releases/wpebackend-fdo-1.0.1.tar.xz
    build-packages:
      - build-essential
      - libegl1
      - libegl-mesa0
      - libegl1-mesa-dev
      - libwayland-egl1
      - libglib2.0-dev
      - libxkbcommon-dev
    stage-packages:
      - libegl1-mesa
      - libwayland-egl1
      - libxkbcommon0

  wpe-webkit:
    after: [wpebackend-fdo]
    # latest stable release
    source: https://wpewebkit.org/releases/wpewebkit-2.22.5.tar.xz
    plugin: cmake
    configflags:
      - -DPORT=WPE
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
      - -GNinja
    build-packages:
      - build-essential
      - gperf
      - ninja-build
      - libcairo2-dev
      - libepoxy-dev
      - libgbm-dev
      - libgcrypt20-dev
      - libgstreamer-plugins-base1.0-dev
      - libicu-dev
      - libjpeg8-dev
      - libsoup2.4-dev
      - libsqlite3-dev
      - libtasn1-6-dev
      - libwebp-dev
      - libwoff-dev
      - libxml2-dev
      - libxslt1-dev
      - pkg-config
      - python
      - ruby-dev
      - wayland-protocols
      # TODO: Are these still required without the minibrowser?
      - weston
      - zlib1g-dev
    stage-packages:
      - libcairo2
      - libepoxy0
      - libgbm1
      - libgl1
      - libglx0
      - libgcrypt20
      - libgstreamer-gl1.0-0
      - libgstreamer-plugins-base1.0-0
      - libharfbuzz-icu0
      - libicu60
      - libjpeg8
      - liborc-0.4-0
      - libsoup2.4-1
      - libsqlite3-0
      - libtasn1-6
      - libwebp6
      - libwebpdemux2
      - libwoff1
      - libxml2
      - libxml2-utils
      - libxslt1.1
      - python
      - ruby
      - zlib1g
      # from https://github.com/Igalia/meta-webkit/blob/e0d5fb3c66b910984464f1f22567a0cd618331ae/recipes-browser/wpewebkit/wpewebkit.inc#L87
      - gstreamer1.0-gl
      - gstreamer1.0-plugins-base
      # FIXME: Pull in only packages referenced in Yocto image to avoid bloat
      - gstreamer1.0-plugins-good
      # - gstreamer1.0-plugins-good-audiofx
      # - gstreamer1.0-plugins-good-audioparsers
      # - gstreamer1.0-plugins-good-autodetect
      # - gstreamer1.0-plugins-good-avi
      # - gstreamer1.0-plugins-good-deinterlace
      # - gstreamer1.0-plugins-good-interleave
      # Runtime requirements for cog browser
      - glib-networking # required for SSL/TLS support
      - glib-networking-common
      - glib-networking-services
      - libgles2
      - libslang2 # dep for gstreamer ASCII art modules ¯\_(ツ)_/¯
      - libgpm2 # mouse
      # TODO: Fix zeroconf/Bonjour name resolution, these don't seem to suffice
      - libavahi-core7
      - libavahi-glib1
      - libavahi-common3
      - libavahi-client3
      # FIXME: Really required on Ubuntu Core?
      - libgl1-mesa-dri
      - mesa-va-drivers
      - libgles2-mesa
      - libglib2.0-bin
    # override-pull: |
    # snapcraftctl pull
    # Add correct compiler macro for clang
    # see https://gcc.gnu.org/ml/gcc-patches/2015-07/msg02237.html
    # Second insertions are source's line number + 1 (from prev insertion)
    # sed -i '143i|| defined(__ARM_ARCH_6KZ__) \\' Source/bmalloc/bmalloc/BPlatform.h
    # sed -i '184i|| defined(__ARM_ARCH_6KZ__) \\' Source/bmalloc/bmalloc/BPlatform.h
    # sed -i '188i|| defined(__ARM_ARCH_6KZ__) \\' Source/WTF/wtf/Platform.h
    # sed -i '236i|| defined(__ARM_ARCH_6KZ__) \\' Source/WTF/wtf/Platform.h
    # override-build: |
    # clang err's because some ruby gluecode cannot determine LP builder's endian type, gcc works
    # export CC=/usr/bin/clang
    # export CXX=/usr/bin/clang++
    # snapcraftctl build
    organize:
      libexec: usr/

  cog:
    after: [wpe-webkit]
    plugin: cmake
    # Build cog offline from checkout since LP builders lose
    # internet access after 2h and wpe-webkit is required
    # for cog build.
    # source: https://github.com/Igalia/cog.git
    # source-tag: v0.2.0
    source: src/cog
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
      - -GNinja
    # stage-packages required by cog at runtime are added in wpe-webkit part
    # due to LP proxy restrictions
    override-prime: |
      snapcraftctl prime
      glib-compile-schemas usr/share/glib-2.0/schemas/
      # see https://stackoverflow.com/questions/28953925/glib-gio-error-no-gsettings-schemas-are-installed-on-the-system
      # creates ca-certificates.crt on build host and copies to snap prime dir
      update-ca-certificates
      cp /etc/ssl/certs/ca-certificates.crt etc/ssl/certs/

  launch-wpe:
    plugin: dump
    source: src/launcher
    organize:
      launch-wpe: bin/
