name: wpe-webkit-mir-kiosk
base: core20
version: "2.30.1" # wpe-webkit release version. TODO: use adopt-info
summary: WPE Webkit in kiosk mode. Intended for mir-kiosk on embedded devices.
description: |
  'WPE Webkit (https://wpewebkit.org) is an official fork of the WebKit project.
  From the website: “WPE WebKit allows embedders to create simple and performant
  systems based on Web platform technologies. It is designed with hardware
  acceleration in mind, leveraging common 3D graphics APIs for best
  performance.”
  This snap runs the included MiniBrowser as a service in kiosk mode.'

grade: stable
confinement: strict

# TODO: Check if these paths can be made relative with compiler flags
layout:
  # Relies on cmake install prefix $SNAP/usr, /libexec is not allowed
  /usr/libexec/wpe-webkit-1.0:
    bind: $SNAP/usr/wpe-webkit-1.0
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/wpe-webkit-1.0:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/wpe-webkit-1.0
  /etc/fonts/conf.avail:
    bind: $SNAP/etc/fonts/conf.avail
  /etc/ssl/certs/ca-certificates.crt:
    bind-file: $SNAP/etc/ssl/certs/ca-certificates.crt
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/local/share/fonts: # wpe-webkit: Search ALL the fonts!
    bind: $SNAP/usr/share/fonts

slots:
  dbus-cogctl:
    interface: dbus
    bus: system
    name: com.igalia.Cog

apps:
  browser:
    command: bin/desktop-launch $SNAP/bin/launch-wpe
    daemon: simple
    restart-condition: always
    slots: [dbus-cogctl]
    plugs:
      # Auto-connected
      - wayland
      - opengl # required for libEGL to work
      - network
      - network-bind # Remote inspector
      - upower-observe
      # Manually connected, show up as AppArmor denials but
      # basic browsing seems to work fine without
      - avahi-observe # zeroconf name resolution
      # snappy-debug suggestions
      - network-manager
      - hostname-control
      - process-control
      # - browser-support # TODO: Use this if/when we can get rid of preload/desktop-launch
  restart-watcher:
    command: bin/watcher.sh
    daemon: simple
    restart-condition: always

    environment:
      LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
      # cf. https://tutorials.ubuntu.com/tutorial/wayland-kiosk#9
      # Liberally adapted from
      # https://github.com/MirServer/mir-kiosk-apps/blob/master/snap/snapcraft.yaml
      # Some might not be needed, but omitting some would either crash
      # the WPE renderer process or cause AppArmor denials
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
      XKB_CONFIG_ROOT: ${SNAP}/usr/share/X11/xkb
      XDG_CONFIG_DIRS: ${SNAP}/etc/xdg:$XDG_CONFIG_DIRS
      XDG_DATA_DIRS: ${SNAP}/usr/share:$XDG_DATA_DIRS
      XDG_DATA_HOME: ${SNAP}/usr/share
      XDG_CACHE_HOME: $SNAP_COMMON/cache
      FONTCONFIG_PATH: ${SNAP}/etc/fonts/conf.d
      FONTCONFIG_FILE: ${SNAP}/etc/fonts/fonts.conf

parts:
  glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

  # See Source/cmake/WebKitFeatures.cmake for build-time options.
  # See Source/cmake/OptionsWPE.cmake for overrides applied by WPE.
  # See Source/cmake/OptionsWPE.cmake for required packages.
  cog:
    plugin: cmake
    source: https://github.com/Igalia/cog.git
    source-tag: v0.8.0
    build-snaps: [wpe-webkit-libs/latest/edge]
    stage-snaps: [wpe-webkit-libs/latest/edge]
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -GNinja
      - -DCOG_DBUS_SYSTEM_BUS=ON
      # - -DWEB_ENGINE_INCLUDE_DIRS=$SNAPCRAFT_PART_INSTALL/usr/include/wpe-webkit-1.0;$SNAPCRAFT_PART_INSTALL/usr/include/wpe-fdo-1.0;$SNAPCRAFT_PART_INSTALL/usr/include/wpe-1.0
    build-packages:
      - ninja-build
      - libcairo2-dev
      - libsoup2.4-dev
      - libxkbcommon-dev
      - libwayland-dev
      - libegl1-mesa-dev
      - wayland-protocols
      - libwayland-bin
      # WPE prebuilt dev packages
      - libwpewebkit-1.0-dev
      - libwpebackend-fdo-1.0-dev
    stage-packages:
      # Runtime requirements for cog browser
      - glib-networking # required for SSL/TLS support
      - glib-networking-common
      - glib-networking-services
      - libgles2
      - libslang2 # dep for gstreamer ASCII art modules ¯\_(ツ)_/¯
      - libgpm2 # mouse
      - libgdk-pixbuf2.0-0
      # TODO: Fix zeroconf/Bonjour name resolution, these don't seem to suffice
      - libavahi-core7
      - libavahi-glib1
      - libavahi-common3
      - libavahi-client3
      - libwayland-cursor0
      # dependencies listed for cog 0.4.0 debian package:
      - libxkbcommon0
      - libegl1
      - libglib2.0-0
      - libsoup2.4-1
      - libwayland-client0
      - libwayland-egl1
      - freeglut3
      - libglu1-mesa
      - shared-mime-info
    override-prime: |
      snapcraftctl prime
      glib-compile-schemas usr/share/glib-2.0/schemas/
      # see https://stackoverflow.com/questions/28953925/glib-gio-error-no-gsettings-schemas-are-installed-on-the-system
      # creates ca-certificates.crt on build host and copies to snap prime dir
      update-ca-certificates
      mkdir -p etc/ssl/certs
      cp /etc/ssl/certs/ca-certificates.crt etc/ssl/certs/
    stage:
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libBrokenLocale-2.31.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libSegFault.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libanl-2.31.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libblkid.so.1.1.0
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libc-2.31.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libcrypt.so.1.1.0
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libdl-2.31.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libgcc_s.so.1
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libm-2.31.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libmemusage.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libmount.so.1.1.0
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libmvec-2.31.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libnsl-2.31.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libnss_compat-2.31.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libnss_dns-2.31.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libnss_files-2.31.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libnss_hesiod-2.31.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libnss_nis-2.31.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libnss_nisplus-2.31.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libpcprofile.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libpcre.so.3.13.3
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libpthread-2.31.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libresolv-2.31.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/librt-2.31.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libselinux.so.1
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libthread_db-1.0.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libutil-2.31.so
      - -lib/$SNAPCRAFT_ARCH_TRIPLET/libz.so.1.2.11
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/audit/sotruss-lib.so
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gconv
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libelf-0.176.so
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libffi.so.7.1.0
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgio-2.0.so.0.6400.3
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libglib-2.0.so.0.6400.3
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgmodule-2.0.so.0.6400.3
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgobject-2.0.so.0.6400.3
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgthread-2.0.so.0.6400.3
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpcre2-8.so.0.9.0
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpcreposix.so.3.13.3
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/glib-2.0/gio-querymodules
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/glib-2.0/glib-compile-schemas
    organize:
      usr/local/: /

  launch-wpe:
    plugin: dump
    source: src/launcher
    organize:
      launch-wpe: bin/

  restart-watcher:
    plugin: dump
    source: src/watcher
    stage-packages:
      - inotify-tools
    organize:
      watcher.sh: bin/
