#!/bin/sh -e

# Initialize configuration with default values
snapctl set \
    url="https://wpewebkit.org" \
    devmode="false" \
    debug="false" \
    error-to-console="false" \
    delay=30

if [ "$(snapctl get daemon)" = "" ]; then
    if grep -q -e snap_core= -e snapd_recovery_mode= /proc/cmdline; then
        snapctl set daemon=true
    else
        snapctl set daemon=false
    fi
fi
